### ISSUE TITLE
Error feedback

### ISSUE THREAD

**Issue by 5igm** [trentech/SimpleChat#6]
```
[15:32:14] [Netty Server IO #3/ERROR] [FML/]: NetworkDispatcher exception
java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
    at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_101]
    at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_101]
    at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_101]
    at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_101]
    at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:285) ~[NioSocketChannel.class:?]
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) [AbstractChannel$AbstractUnsafe.class:?]
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:321) [AbstractNioChannel$AbstractNioUnsafe.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:519) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[15:32:15] [Netty Server IO #3/WARN] [io.netty.channel.DefaultChannelPipeline/]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
    at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_101]
    at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_101]
    at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_101]
    at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_101]
    at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:285) ~[NioSocketChannel.class:?]
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) [AbstractChannel$AbstractUnsafe.class:?]
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:321) [AbstractNioChannel$AbstractNioUnsafe.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:519) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by 5igm** [comment]
simplechat-5.0.0-0.4.0
spongeforge-1.8.9-1890-4.2.0-BETA-1666

**Comment by trentech** [comment]
No idea what this error is. There's no mention of this plugin. It's doesn't look related
